config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#all_accounts'
  get  'deposit' => 'accounts#deposit'
  get 'withdrawal' => 'accounts#withdrawal'
  post 'update_balance' =>'accounts#update_balance'
  get 'transfer' => 'accounts#transfer'
  post 'complete_transfer' => 'accounts#complete_transfer'

  resources :accounts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def all_accounts
  	if current_user.role == 'admin'
  		@accounts = Account.all
  	else
  		@accounts = Account.where(user_id: current_user.id)	
  	end	
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/all_accounts.html.erb
<h1>Welcome to Your Dashboard, <%= current_user.first_name %>!</h1>


 <p id="notice"><%= notice %></p>
 <p id="alert"><%= alert %></p>


<p>Here are your accounts at a glance:</p>

<table class='table'>
  <thead>
    <tr>
    	<th>Account Number</th>
    	<% if current_user.role == 'admin' %>
    		<th>First Name</th>
    		<th>Last Name</th>
    	<% end %>	
      <th>Balance</th>
      <th>Account type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
      	<td><%= account.id %></td>
      	<% if current_user.role == 'admin' %>
	    		<td><%= account.user.first_name %></td>
	    		<td><%= account.user.last_name %></td>
	    	<% end %>	
        <td><%= number_to_currency account.balance %></td>
        <td><%= account.account_type %></td>
        <td><%= link_to 'Transactions', account, class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
	<p><%= link_to 'Open a New Account', new_account_path, class: 'btn btn-success btn-lg' %></p>
  
</div>